[package]
name = "zincha-cli"
description = "Public Zincha developer CLI."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[[bin]]
name = "zincha"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
tokio.workspace = true
zincha-cli-core = { path = "../zincha-cli-core" }

