[package]
name = "zincha-client"
description = "HTTP and WebSocket client helpers for the Zincha chain."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
anyhow.workspace = true
futures.workspace = true
hex.workspace = true
rand.workspace = true
reqwest.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
url.workspace = true
webpki-roots.workspace = true
zincha-primitives = { path = "../zincha-primitives" }
