[package]
name = "zincha-client"
description = "HTTP and WebSocket client helpers for the Zincha chain."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
anyhow.workspace = true
async-stream.workspace = true
base64.workspace = true
chacha20poly1305.workspace = true
ed25519-dalek.workspace = true
futures.workspace = true
hex.workspace = true
hkdf.workspace = true
rand.workspace = true
reqwest.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_jcs.workspace = true
sha2.workspace = true
subtle.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
url.workspace = true
uuid.workspace = true
webpki-roots.workspace = true
x25519-dalek.workspace = true
x509-parser.workspace = true
zincha-primitives = { path = "../zincha-primitives" }

[dev-dependencies]
h2.workspace = true
http.workspace = true
rcgen.workspace = true
tokio-rustls.workspace = true
