[package]
name = "zincha-cli-core"
description = "Shared public CLI command implementation for Zincha."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
anyhow.workspace = true
bincode.workspace = true
clap.workspace = true
hex.workspace = true
rpassword.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
zincha-client = { path = "../zincha-client" }
zincha-primitives = { path = "../zincha-primitives" }
